/*
  ==============================================================================

  This file was auto-generated by the Introjucer!

  It contains the basic framework code for a JUCE plugin processor.

  ==============================================================================
  */

#include "PluginProcessor.h"
#include "PluginEditor.h"

#include <cmath>


//==============================================================================
BlankenhainAudioProcessor::BlankenhainAudioProcessor()
{
}

BlankenhainAudioProcessor::~BlankenhainAudioProcessor()
{
}

//==============================================================================
const String BlankenhainAudioProcessor::getName() const
{
	return JucePlugin_Name;
}

int BlankenhainAudioProcessor::getNumParameters()
{
	return 0;
}

float BlankenhainAudioProcessor::getParameter(int index)
{
	return 0.0f;
}

void BlankenhainAudioProcessor::setParameter(int index, float newValue)
{
}

const String BlankenhainAudioProcessor::getParameterName(int index)
{
	return String();
}

const String BlankenhainAudioProcessor::getParameterText(int index)
{
	return String();
}

const String BlankenhainAudioProcessor::getInputChannelName(int channelIndex) const
{
	return String(channelIndex + 1);
}

const String BlankenhainAudioProcessor::getOutputChannelName(int channelIndex) const
{
	return String(channelIndex + 1);
}

bool BlankenhainAudioProcessor::isInputChannelStereoPair(int index) const
{
	return true;
}

bool BlankenhainAudioProcessor::isOutputChannelStereoPair(int index) const
{
	return true;
}

bool BlankenhainAudioProcessor::acceptsMidi() const
{
#if JucePlugin_WantsMidiInput
	return true;
#else
	return false;
#endif
}

bool BlankenhainAudioProcessor::producesMidi() const
{
#if JucePlugin_ProducesMidiOutput
	return true;
#else
	return false;
#endif
}

bool BlankenhainAudioProcessor::silenceInProducesSilenceOut() const
{
	return false;
}

double BlankenhainAudioProcessor::getTailLengthSeconds() const
{
	return 0.0;
}

int BlankenhainAudioProcessor::getNumPrograms()
{
	return 1;   // NB: some hosts don't cope very well if you tell them there are 0 programs,
	// so this should be at least 1, even if you're not really implementing programs.
}

int BlankenhainAudioProcessor::getCurrentProgram()
{
	return 0;
}

void BlankenhainAudioProcessor::setCurrentProgram(int index)
{
}

const String BlankenhainAudioProcessor::getProgramName(int index)
{
	return String();
}

void BlankenhainAudioProcessor::changeProgramName(int index, const String& newName)
{
}

//==============================================================================
void BlankenhainAudioProcessor::prepareToPlay(double sampleRate, int samplesPerBlock)
{
	// Use this method as the place to do any pre-playback
	// initialisation that you need..
}

void BlankenhainAudioProcessor::releaseResources()
{
	// When playback stops, you can use this as an opportunity to free up any
	// spare memory, etc.
}

void BlankenhainAudioProcessor::processBlock(AudioSampleBuffer& buffer, MidiBuffer& midiMessages)
{
	// In case we have more outputs than inputs, this code clears any output
	// channels that didn't contain input data, (because these aren't
	// guaranteed to be empty - they may contain garbage).
	// I've added this to avoid people getting screaming feedback
	// when they first compile the plugin, but obviously you don't need to
	// this code if your algorithm already fills all the output channels.
	for (int i = getNumInputChannels(); i < getNumOutputChannels(); ++i)
		buffer.clear(i, 0, buffer.getNumSamples());

	// This is the place where you'd normally do the guts of your plugin's
	// audio processing...
	/*
	for (int channel = 0; channel < getNumInputChannels(); ++channel)
	{
	float* channelData = buffer.getWritePointer(channel);

	// ..do something to the data...
	}
	*/

	MidiBuffer::Iterator iterator(midiMessages);
	MidiMessage message;
	int samplePosition;
	int bufferPosition = 0;
	if (!midiMessages.isEmpty()) {
		Logger::outputDebugString("List midi events");
	}
	while (iterator.getNextEvent(message, samplePosition)) {
		if (message.isNoteOnOrOff()) {
			String onOff = message.isNoteOn() ? "On" : "Off";
			Logger::outputDebugString(onOff + " " + String(message.getNoteNumber()) + " " + String(samplePosition));
			float** data = buffer.getArrayOfWritePointers();
			for (; bufferPosition < samplePosition; bufferPosition++) {
				const float value = getADSRValue();
				for (int channel = 0; channel < getNumOutputChannels(); channel++) {
					data[channel][bufferPosition] = value;
				}
				timeSinceTrigger++;
				timeSinceRelease++;
			}
			if (message.isNoteOn()) {
				noteOn = true;
				lastNoteNumber = message.getNoteNumber();
				lastNote = MidiMessage::getMidiNoteInHertz(lastNoteNumber);
				timeSinceTrigger = 0;
			}
			else if (lastNoteNumber == message.getNoteNumber()) {
				noteOn = false;
				timeSinceRelease = 0;
			}
		}
		else {
			Logger::outputDebugString("Other event");
		}
	}
	float** data = buffer.getArrayOfWritePointers();
	for (; bufferPosition < buffer.getNumSamples(); bufferPosition++) {
		const float value = getADSRValue();
		for (int channel = 0; channel < getNumOutputChannels(); channel++) {
			data[channel][bufferPosition] = value;
		}
		timeSinceTrigger++;
		timeSinceRelease++;
	}
}

//==============================================================================
bool BlankenhainAudioProcessor::hasEditor() const
{
	return true; // (change this to false if you choose to not supply an editor)
}

AudioProcessorEditor* BlankenhainAudioProcessor::createEditor()
{
	return new BlankenhainAudioProcessorEditor(this);
}

//==============================================================================
void BlankenhainAudioProcessor::getStateInformation(MemoryBlock& destData)
{
	// You should use this method to store your parameters in the memory block.
	// You could do that either as raw data, or use the XML or ValueTree classes
	// as intermediaries to make it easy to save and load complex data.
}

void BlankenhainAudioProcessor::setStateInformation(const void* data, int sizeInBytes)
{
	// You should use this method to restore your parameters from this memory block,
	// whose contents will have been created by the getStateInformation() call.
}

float BlankenhainAudioProcessor::getADSRValue() const {
	const double TAU = 6.283185;
	const double attack = 200. / 1000 * getSampleRate();
	const double decay = 200. / 1000 * getSampleRate();
	const double sustain = .5;
	const float release = 200. / 1000 * getSampleRate();

	float factor = sustain;
	if (noteOn) {
		if (timeSinceTrigger <= attack) {
			factor = timeSinceTrigger / attack;
		}
		else if (timeSinceTrigger - attack <= decay) {
			const double t = (timeSinceTrigger - attack) / decay;
			factor = (1 - t) + sustain * t;
		}
	}
	else {
		if (timeSinceRelease <= release) {
			const double t = timeSinceRelease / release;
			factor = sustain * (1 - t);
		}
		else {
			factor = 0.;
		}
	}

	return factor * std::sin(double(timeSinceTrigger) / getSampleRate() * lastNote * TAU);
}

//==============================================================================
// This creates new instances of the plugin..
AudioProcessor* JUCE_CALLTYPE createPluginFilter()
{
	return new BlankenhainAudioProcessor();
}
